# Generated by Django 5.1.5 on 2025-11-04 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algebrai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(default='TBD', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='algebrai.lesson'),
        ),
        migrations.AlterField(
            model_name='option',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='algebrai.exercise'),
        ),
    ]
