# Generated by Django 5.2.8 on 2025-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algebrai', '0002_remove_exercise_difficulty_exercise_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
